[supabase]
url = "https://njbvzqfjilxruihmeyyd.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qYnZ6cWZqaWx4cnVpaG1leXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzY3NzAsImV4cCI6MjA2ODI1Mjc3MH0.XE8itLG5qxvPjjQ6sLE9vMW7C42wyYclxSe2IlD_sXc"
[gemini]
api_key="AIzaSyAqPBRteDaydaTEe7qzSV6vpaN9_X3WsAg"